import { Link, Route, Routes, useParams, useNavigate } from 'react-router-dom';
import { useEffect, useState } from 'react';
import { db } from '../db/database';import type { FieldItem, Group, ItemType, User } from '../models/types';import { useAppStore } from '../stores/appStore';import { id } from '../utils/id';
const itemTypes:ItemType[]=['RFI','NC','PLI','OBS','HAZ','NM','INC','ACC','ACT','INS','FOT','VID','DOC'];
export default function App(){return <div className='app'><aside className='sidebar'><h2>FieldChat PoC</h2><nav className='row'><Link to='/'>Grupos</Link><Link to='/settings'>Settings</Link></nav></aside><main className='main'><Routes><Route path='/' element={<Groups/>}/><Route path='/groups/:groupId' element={<GroupDetail/>}/><Route path='/items/:itemId' element={<ItemDetail/>}/><Route path='/new/:groupId' element={<NewItem/>}/><Route path='/settings' element={<Settings/>}/></Routes></main></div>}
function Groups(){const [groups,setGroups]=useState<Group[]>([]);useEffect(()=>{db.groups.toArray().then(setGroups)},[]);return <>{groups.map(g=><div className='card' key={g.id}><Link to={`/groups/${g.id}`}><b>{g.name}</b></Link><div>{g.description}</div></div>)}</>}
function GroupDetail(){const {groupId=''}=useParams();const [items,setItems]=useState<FieldItem[]>([]);const [type,setType]=useState('ALL');useEffect(()=>{db.fieldItems.where('group_id').equals(groupId).toArray().then(v=>setItems(v.sort((a,b)=>b.updated_at.localeCompare(a.updated_at))) )},[groupId]);const shown=type==='ALL'?items:items.filter(i=>i.item_type===type);return <div><Link to={`/new/${groupId}`} className='btn'>+ Nuevo ítem</Link><div className='row' style={{margin:'10px 0'}}><button className='btn' onClick={()=>setType('ALL')}>Todos</button>{itemTypes.map(t=><button key={t} className='btn' onClick={()=>setType(t)}>{t}</button>)}</div>{shown.map(i=><div className='card' key={i.id}><Link to={`/items/${i.id}`}><b>{i.item_number}</b> - {i.title}</Link><div className='row'><span className='badge'>{i.item_type}</span><span className='badge'>{i.status}</span></div></div>)}</div>}
function ItemDetail(){const {itemId=''}=useParams();const uid=useAppStore(s=>s.activeUserId);const [item,setItem]=useState<FieldItem|null>(null);const [comments,setComments]=useState<any[]>([]);const [txt,setTxt]=useState('');useEffect(()=>{db.fieldItems.get(itemId).then(setItem);db.itemComments.where('item_id').equals(itemId).toArray().then(setComments)},[itemId]);if(!item)return null;return <div><h3>{item.item_number} · {item.title}</h3><select className='select' value={item.status} onChange={async e=>{const n=e.target.value;await db.fieldItems.update(item.id,{status:n,updated_at:new Date().toISOString()});setItem({...item,status:n});}}>{['Open','Assigned','In Progress','Closed','Submitted','Under Review','Answered','Reported'].map(s=><option key={s}>{s}</option>)}</select>{comments.map(c=><div className='card' key={c.id}>{c.comment_text}</div>)}<textarea value={txt} onChange={e=>setTxt(e.target.value)} /><button className='btn' onClick={async()=>{if(!txt.trim())return;const now=new Date().toISOString();await db.itemComments.add({id:id('c'),item_id:item.id,group_id:item.group_id,comment_text:txt.trim(),created_by:uid,created_at:now});setComments(await db.itemComments.where('item_id').equals(item.id).toArray());setTxt('');}}>Comentar</button></div>}
function NewItem(){const {groupId=''}=useParams();const nav=useNavigate();const uid=useAppStore(s=>s.activeUserId);const [form,setForm]=useState({item_type:'RFI',title:'',description:'',status:'Open',priority:'Medium'});return <div><h3>Nuevo Field Item</h3><select className='select' value={form.item_type} onChange={e=>setForm({...form,item_type:e.target.value})}>{itemTypes.map(t=><option key={t}>{t}</option>)}</select><input className='input' placeholder='Título' value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><textarea className='input' placeholder='Descripción' value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><button className='btn' onClick={async()=>{const now=new Date().toISOString();const count=await db.fieldItems.where('group_id').equals(groupId).count();const prefix=form.item_type;await db.fieldItems.add({id:id('i'),group_id:groupId,item_number:`${prefix}-${String(count+1).padStart(3,'0')}`,item_type:form.item_type as ItemType,title:form.title,description:form.description,status:form.status,priority:form.priority,created_by:uid,created_at:now,updated_at:now,has_pdf_reference:false,has_droppin:false,is_general_item:true});nav(`/groups/${groupId}`);}}>Guardar</button></div>}
function Settings(){const {activeUserId,setActiveUserId}=useAppStore();const [users,setUsers]=useState<User[]>([]);useEffect(()=>{db.users.toArray().then(setUsers)},[]);return <div><h3>Usuario activo</h3><select className='select' value={activeUserId} onChange={e=>setActiveUserId(e.target.value)}>{users.map(u=><option key={u.id} value={u.id}>{u.display_name} · {u.role}</option>)}</select></div>}
